### ISSUE TITLE
Wrong conclusion based upon density plot in basic tutorial vignette

### ISSUE THREAD

**Issue by FrieseWoudloper** [ModelOriented/fairmodels#26]
In the Basic Tutorial vignette in [1.3.2](https://cran.r-project.org/web/packages/fairmodels/vignettes/Basic_tutorial.html#132_plot_density) it says:

> As we can see it is more likely that model will categorize African Americans as not being recidivists than for example Asians.

But the positive label is 'not being a recidivist'. So shouldn't it be the other way around? 

> As we can see it is more likely that the model will categorize African Americans as being recidivists than for example Asians.

**Comment by jakwisn** [comment]
Yes, it's right. As we are predicting **not** being a recidivist the African Americans in that model will be less likely to be classified as non-recidivists.
