### ISSUE TITLE
fobject$group_data in basic tutorial vignette returns NULL

### ISSUE THREAD

**Issue by FrieseWoudloper** [ModelOriented/fairmodels#28]
In the basic tutorial vignette in [1.3.3](https://cran.r-project.org/web/packages/fairmodels/vignettes/Basic_tutorial.html#133_Metric_scores_plot) it says:

> User could use `fobject$group_data`

but executing this statement actually returns `NULL`.

**Comment by jakwisn** [comment]
Thanks, I left `s` there, it should be `fobject$groups_data`
