### ISSUE TITLE
Difficulty figuring out valid values for fairness_metrics argument in metric_scores function

### ISSUE THREAD

**Issue by FrieseWoudloper** [ModelOriented/fairmodels#29]
It was difficult for me to figure out valid values for the `fairness_metrics` argument for the function `metric_scores`. The _Usage_ section of the help says:

> `metric_scores(x, fairness_metrics = fairness_check_metrics())`

However, `fairness_check_metrics` is a helper function that is not exposed. So I don't think it should be mentioned.

Also the _Arguments_ section says:

> `fairness_metrics`	character, vector with fairness metric names. Default metrics are ones in `fairness_check` plot

However, the plot doesn't give the exact valid argument values.

From the _Examples_ section:

> ms <- metric_scores(fobject, fairness_metrics = c("TPR","STP","ACC"))

The meaning of TPR and ACC I could easily guess, but for me it wasn't immediately clear what STP stands for.

So maybe it would be better to explicitly state all valid values, including a full description?

**Comment by jakwisn** [comment]
Hi @FrieseWoudloper, thanks for all the issues! I changed `fairness_check_metrics()` to explicitly stating metrics `c('ACC', 'TPR', 'PPV', 'FPR', 'STP')`, I think it will be helpful. I know that these metric names abbreviations are sometimes difficult to decipher so now when a user has to state some metric name, the documentation will point to the `fairness_check` function documentation, where every abbreviation is explained. I also did changes according to your other issues (#26 , #27, #28). Thanks for using `fairmodels`.
