### ISSUE TITLE
Passing only fairness_objects to fairness_check

### ISSUE THREAD

**Issue by katherineking4** [ModelOriented/fairmodels#36]
I was trying to pass three fairness objects into fairness_check to plot them all at once. This was the error I received: 
_Error in fairness_check(fairness_train_sex_cutoff, protected = analysis_train$sex,  : 
  object 'parity_loss' not found_

It looks like when an explainer is not passed to fairness_check the parity loss object is not created but the names of this object are referenced later [_colnames(parity_loss_metric_data) <- names(parity_loss)_] so the function fails

**Comment by jakwisn** [comment]
Thanks for the issue! The bug should be now fixed.
