### ISSUE TITLE
Can we use range of values (1-5) for a protected variable

### ISSUE THREAD

**Issue by neuideas** [ModelOriented/fairmodels#46]
Hi everyone, hope you are fine.

About fairmodels, I have an input metric with values from 1-30 (I make it from numeric to nominal) which I want to put as a protected variable. We can evaluate its fairness for individual values (e.g. 1, 2, 3 or so) but can we check it for a range of values. I mean what if we want to check the fairness of a model like: This model has less fairness when the protected variable has a range 1-6 and has less bias when the range of values is between 15-25. 

I know this case might be different than originally the package has developed for but just asking if it is possible to implement.?

Thanks

**Comment by jakwisn** [comment]
Hi, 
what about making a vector with 3 levels: `1-6`, `5,25`, and `other`? Would that do the job?

**Comment by neuideas** [comment]
Thank you Jakub.

One vector with three levels? Then how can we access it with the "if
statement" and assign the values to a protected variable? Or we should take
three vectors separately with three levels:

vec1= c(1:5)
vec2= c( 12:14, 17)
vec3= c(21:24)

**Comment by jakwisn** [comment]
I mean, you can create a whole new vector with just those three values. Protected variable is just a vector.
So depending on your previous vector just create a new one with mapped values. 
like
`c(1, 2, 4, 16, 17, 30, 29)` would be `c(a, a, a, b, b, c, c)`
  
and you pass new vector as protected

**Comment by neuideas** [comment]
Thank you Jakub.. I will try it.

You can close the issue.

Regards
