### ISSUE TITLE
Basic question about fairmodel

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/fairmodels#47]
Hi Jakub and other members, I have two questions about the basic concept of fairmodels ..

(1) Can we use any variable of a dataset as a protected variable which is either binary or nominal?

(2) Is there any way we use a continuous variable (with as much as 1000 different values) as a protected variable? 

(3) I have an input variable which has values 9 and 13.. I used the fairmodel and found that there is no unprivileged value i.e. almost all the metrics fall in the green region. Would it be a good idea to use different class-balancing techniques and see if they (inclusion/exclusion of instances) impact the fairness of the model.?

**Comment by jakwisn** [comment]
Hi, answering your questions:
1. Yes 
2. Yes, but it will be treated as a discrete one and I am not sure that 1000 values will be visible on the plot. Better to make some levels like `0-100`, `101-500`, `501-1000`. 
3. Why not, It would be an interesting piece of research.

**Comment by Nehagupta90** [comment]
Thanks a lot Jakub for your information.
