### ISSUE TITLE
Disparact_impact_remover

### ISSUE THREAD

**Issue by noora-maki** [ModelOriented/fairmodels#50]
I tried different datasets, the following error always occurred,

![Screenshot 2023-02-22 at 19 54 43](https://user-images.githubusercontent.com/25897898/220744050-d76f448d-eb0d-4aa8-9903-8d8bac17d8d8.png)

**Comment by jakwisn** [comment]
Hi @noora-maki! 
Can you provide a working snippet of code where an error could be reproduced?

**Comment by noora-maki** [comment]
> Hi @noora-maki! Can you provide a working snippet of code where an error could be reproduced?

Thanks for response.

I just imported the dataset (attached).
[1.xlsx](https://github.com/ModelOriented/fairmodels/files/10812135/1.xlsx)
The protected attribute is sex, 

> X1$sex <- as.factor(X1$sex)

and then try applying pre-processing techniques to this dataset,

X1_changed <- disparate_impact_remover(
  data = X1,
  protected = X1$sex,
  features_to_transform = 'age',
  lambda = 1
)
Then the error occurred.
![Screenshot 2023-02-23 at 09 36 26](https://user-images.githubusercontent.com/25897898/220870094-6bc30693-441e-42be-8f40-3f4945d6b9db.png)

**Comment by jakwisn** [comment]
@noora-maki 
data must be in the form of a dataframe. Try doing 
```
X1 <- as.data.frame(read_excel("1.xlsx"))   
```
Hope it helps

**Comment by noora-maki** [comment]
Thanks! That works!! I'll close it. 
Thanks a million.
